#!/usr/bin/env bash
# cleanup-instructions.sh
# Prints a step-by-step cleanup guide for finalizing the repository.
# This script PRINTS instructions -- it does NOT execute any destructive commands.
# Follow each step manually after reviewing what it does.
#
# Usage:
#   ./cleanup-instructions.sh

# ── Load platform detection helpers ──────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../scripts/platform-detect.sh"

echo "=== Phase 13: Cleanup Instructions ==="
echo ""
echo "Follow these steps manually to finalize your repository."
echo "Each step is printed for review -- nothing is executed automatically."
echo ""
echo "────────────────────────────────────────────────────────────────────"
echo ""

echo "STEP 1: Unstage any accidentally staged files"
echo ""
echo "  If you ran 'git add .' and staged test files or settings:"
echo ""
echo "    git reset HEAD ."
echo ""
echo "  Then re-add only the files you intend to commit:"
echo ""
echo "    git add diagrams/ phase-*/  # adjust paths as needed"
echo ""
echo "────────────────────────────────────────────────────────────────────"
echo ""

echo "STEP 2: Remove test diagrams from diagrams/"
echo ""
echo "  Delete any scratch or test files created during setup:"
echo ""
echo "    # List candidates first:"
echo "    ls diagrams/test-* diagrams/*-test.* 2>/dev/null"
echo ""
echo "    # Then delete:"
echo "    rm diagrams/test-*.mmd diagrams/test-*.svg diagrams/test-*.png"
echo ""
echo "  Keep only diagram files that belong in the final repo."
echo ""
echo "────────────────────────────────────────────────────────────────────"
echo ""

echo "STEP 3: Add .claude/settings.local.json to .gitignore"
echo ""
echo "  settings.local.json contains machine-specific hook paths and should"
echo "  never be committed. Add it to .gitignore if not already present:"
echo ""
echo "    echo '.claude/settings.local.json' >> .gitignore"
echo ""
echo "  Verify it's excluded:"
echo ""
echo "    git check-ignore -v .claude/settings.local.json"
echo ""
echo "────────────────────────────────────────────────────────────────────"
echo ""

echo "STEP 4: Verify git status is clean"
echo ""
echo "  Check what will be committed:"
echo ""
echo "    git status"
echo "    git diff --staged"
echo ""
echo "  Make sure no secrets, large binaries, or test files are staged."
echo ""
echo "────────────────────────────────────────────────────────────────────"
echo ""

echo "STEP 5: Create the final commit"
echo ""
echo "  Commit only intentional changes using conventional commit format:"
echo ""
echo "    git add diagrams/ phase-*/"
echo "    git commit -m 'feat: complete Mermaid hybrid stack guide (Phases 0-13)'"
echo ""
echo "  Or commit incrementally per phase for cleaner history:"
echo ""
echo "    git commit -m 'feat: add Phase 9 HTML embedding scripts'"
echo "    git commit -m 'feat: add Phase 10 Vega-Lite integration'"
echo "    git commit -m 'feat: add Phase 11 D2 architecture diagrams'"
echo "    git commit -m 'docs: add Phase 12 MCP evaluation rejection'"
echo "    git commit -m 'feat: add Phase 13 validation and cleanup scripts'"
echo ""
echo "────────────────────────────────────────────────────────────────────"
echo ""

echo "STEP 6: Confirm infrastructure is excluded from the repo"
echo ""
echo "  The following live OUTSIDE the repo and should NOT be committed:"
echo ""
echo "    ~/bin/mermaid-render       (Phase 1)"
echo "    ~/bin/vegalite-render      (Phase 10)"
echo "    ~/bin/d2-render            (Phase 11)"
echo "    ~/bin/render-all-diagrams  (Phase 13)"
echo "    ~/.claude/settings.json    (global skill + hooks)"
echo ""
echo "  These persist on your machine and survive repo clones."
echo "  Document them in the project README so future collaborators"
echo "  know to run the install scripts to recreate them."
echo ""
echo "────────────────────────────────────────────────────────────────────"
echo ""

echo "=== Cleanup instructions complete. ==="
echo "See configs/cleanup-checklist.example for a printable checklist."
