#!/usr/bin/env bash
# test-pdf-pipeline.sh
# Smoke-tests the PDF pipeline end-to-end:
#   1. Creates a test .mmd diagram
#   2. Renders it to PNG at 3x scale
#   3. Creates a test markdown file that references the PNG
#   4. Converts the markdown to PDF (or HTML fallback) with mermaid-pdf
#   5. Verifies the output file exists and is non-empty

set -euo pipefail

# ── Load platform helpers ────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../scripts/platform-detect.sh"

PASS=0
FAIL=0

pass() { echo "  PASS -- $1"; PASS=$((PASS + 1)); }
fail() { echo "  FAIL -- $1"; FAIL=$((FAIL + 1)); }

# ── Prereq checks ─────────────────────────────────────────────────────────────
echo "==> Checking prerequisites..."

for cmd in pandoc mermaid-render; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "ERROR: '$cmd' not found. Run the relevant install/create script first." >&2
        exit 1
    fi
done

if [ ! -x "$HOME/bin/mermaid-pdf" ]; then
    echo "ERROR: ~/bin/mermaid-pdf not found. Run create-pdf-script.sh first." >&2
    exit 1
fi

export PATH="$HOME/bin:$PATH"

# ── Temp workspace ────────────────────────────────────────────────────────────
TMPDIR_TEST="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_TEST"' EXIT

echo "==> Test workspace: $TMPDIR_TEST"
echo ""

# ── Step 1: Create a test diagram ─────────────────────────────────────────────
echo "--> Step 1: Create test diagram"
TEST_MMD="$TMPDIR_TEST/pipeline-test.mmd"

cat > "$TEST_MMD" << 'EOF'
flowchart TD
    A["Markdown Source"] --> B["pandoc"]
    B --> C["PDF Output"]
    D["Mermaid Diagram"] --> E["mermaid-render -s 3"]
    E --> F["3x PNG"]
    F --> B
EOF

if [ -f "$TEST_MMD" ]; then
    pass "test diagram created"
else
    fail "failed to create test diagram"
fi

# ── Step 2: Render the diagram to PNG at 3x ───────────────────────────────────
echo "--> Step 2: Render diagram to PNG at 3x scale"
TEST_PNG="$TMPDIR_TEST/pipeline-test.png"

if mermaid-render "$TEST_MMD" "$TEST_PNG" -s 3 2>/dev/null; then
    pass "diagram rendered to 3x PNG"
else
    fail "mermaid-render failed -- check Docker/mermaid-cli setup"
fi

# ── Step 3: Create a test markdown file ──────────────────────────────────────
echo "--> Step 3: Create test markdown document"
TEST_MD="$TMPDIR_TEST/test-document.md"

cat > "$TEST_MD" << MDEOF
# PDF Pipeline Test Document

This document was generated by test-pdf-pipeline.sh to verify that
the mermaid-pdf pipeline produces a valid PDF output.

## Diagram

The diagram below was rendered by mermaid-render at 3x scale:

![PDF Pipeline Flowchart](pipeline-test.png)

## Pipeline Steps

1. Write a Mermaid diagram as a \`.mmd\` file
2. Run \`render-all-diagrams\` to produce 3x PNG files
3. Reference the PNG in your markdown with standard image syntax
4. Run \`mermaid-pdf document.md\` to convert to PDF

## Notes

- 3x scale produces ~288 DPI equivalent -- sharp at any PDF zoom level
- SVG output is also generated for web/GitHub use
- pandoc handles the markdown-to-PDF conversion with geometry settings
MDEOF

if [ -f "$TEST_MD" ]; then
    pass "test markdown created"
else
    fail "failed to create test markdown"
fi

# ── Step 4: Run mermaid-pdf ───────────────────────────────────────────────────
echo "--> Step 4: Run mermaid-pdf"
TEST_PDF="$TMPDIR_TEST/test-document.pdf"
TEST_HTML="$TMPDIR_TEST/test-document.html"

# Run from within the temp dir so relative image paths resolve correctly.
OUTPUT="$(cd "$TMPDIR_TEST" && "$HOME/bin/mermaid-pdf" test-document.md 2>&1 || true)"
echo "    pandoc output: $OUTPUT"

# ── Step 5: Verify output ─────────────────────────────────────────────────────
echo "--> Step 5: Verify output exists and is non-empty"

if [ -f "$TEST_PDF" ] && [ -s "$TEST_PDF" ]; then
    SIZE="$(du -h "$TEST_PDF" | cut -f1)"
    pass "PDF created: test-document.pdf ($SIZE)"
elif [ -f "$TEST_HTML" ] && [ -s "$TEST_HTML" ]; then
    SIZE="$(du -h "$TEST_HTML" | cut -f1)"
    pass "HTML fallback created: test-document.html ($SIZE) -- open in browser to print-to-PDF"
else
    fail "no output file produced -- check pandoc and backend installation"
fi

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "================================"
echo "Results: $PASS passed, $FAIL failed"
echo "================================"

if [ "$FAIL" -gt 0 ]; then
    exit 1
fi
